services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: lego
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: legodb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
